version: "3"

networks:
    jnmmicrolivenetwork:
        external: false

services:
    server:
        image: jnmdev/twitterlive:latest
        restart: always
        container_name: jnmmicro
        environment:
            - Instance:Domain=jnmmicro.io
            - Instance:AdminEmail=j@jnm.io
            - Db:Type=postgres
            - Db:Host=db
            - Db:Name=jnmmicro
            - Db:User=jnmmicro
            - Db:Password=jnmmicro
            - Twitter:ConsumerKey=VX7gB9IVIuGzpkRpvUCsMLN4u
            - Twitter:ConsumerSecret=D4Ams5FjNlyXbDZpsl7Uh3gxo11o3lYeZnEbnYjg5ssnWHwUa7
        networks:
            - jnmmicrolivenetwork
        ports:
            - "5000:80"
        depends_on:
            - db

    db:
        image: postgres:9.6
        restart: always
        environment:
            - POSTGRES_USER=jnmmicro
            - POSTGRES_PASSWORD=jnmmicro
            - POSTGRES_DB=jnmmicro
        networks:
            - jnmmicrolivenetwork
        volumes:
            - ./postgres:/var/lib/postgresql/data